# Generated by Django 4.2.7 on 2023-11-28 22:40

import detection.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=detection.models.upload_directory_org, verbose_name='imagem original')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to=detection.models.upload_directory_res, verbose_name='imagem original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
        ),
    ]
